language: java

addons:
  sonarcloud:
    organization: "jackgoldsworth-github"
    token:
      secure: "ntG8fF0QkI1CgYnZ04Oyn2AuLKL12poNregk/HkIksVdOtUarnGSshUR8mw94j6JlWY4DOujhdKVDfTvVrpmMZ5Y4EqotW9eRTpaXvvIwm9JGAn0R+UHSel9dDZfGAN6fjvfsBRta2evySs2sF+R0eKRcwjRLtiYjn9NeQL2rz40eey6bFfxWQz0TuPeRmUUbdXSoqDfzRhN8u6BQbRDBq5A2UaI4QSQ/RxlZhRAPgws/4Nu8d17lhBjZhkA7jP9NeZtusBrFuHCwHVwJ6lWZY7AWY3vqFfS5DoPFPYmLIAAIMOuB7JXisHXUV/kvfmlxBjNomOKGOqYpR7iqCzK5HaxUBTN4jOPm/j7w8AdEPdUvQqFlXS/joG4vLe3b//KB04a3C5xP6ab7iMVQQXJ66lnCvhsL0GmPO3kXBbbF6ImiUojhbgpxMdNlEZcsE8C3TQbmDWhlQApkz/i+BQmJpFl/keQnV9UClCYz5/xo1P1YUjyr0g9EcH07z+zHf5ru3ltMIAvS+Zq+nwgVA98cEbI4mZUhLPDWWayle3dtDsuXiTUWeapMf8pVPGFxfUSYj90dc4nVrFtZ1awTpoS7OEKgaQVV7EDNwXM4dThQII5OYScjODrIgoc9DSqzwC7JOcFKvYM5tYvYXXSKsVvuBhHngWuuLqClg0230V3aK0="

jdk:
  - openjdk8

install:
  - true

script:
  - "./gradlew sonarqube"

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
